version: 0.2

phases:
  install:
    commands:
      - echo "Starting installation..."
      - npm install
  build:
    commands:
      - echo "Starting build..."
     
  post_build:
    commands:
      - echo "Build completed."
artifacts:
  files:
    - '**/*'
  